class CustomUtils:
    SUCCESSFULL = 1
    SOMETHING_WENT_WRONG = -1
    WRONG_CREDENTIALS = -2
    EMPLOYEE_DOSENT_HAS_RIGHT = -3
    EMPLOYEE_NOT_LOGGED_IN = -4
    PACKAGE_DOES_NOT_EXIST = -5
    CUSTOMER_DOES_NOT_EXIST = -6
    EMAIL_SENDING_FAILED = -7
    EMPLOYEE_WITH_EMAIL_NOT_EXIST = -8
    CUSTOMER_NOT_LOGGED_IN = -9
